Homework 1
infinum-academy/js-react-academy-2024-bokii2 pull request #1
Opened 2024-07-03 23:03 UTC by bokii2

2024-07-04 14:00 UTC, ante-pesorda requested changes

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.html
> +        <link rel="stylesheet" href="styles.css">
Dodati favicon

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.html
> +                    <!-- <input id="reviewRating" type="number" name="rating" placeholder="Add rating" min="0" max="5"> -->
Počistiti

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.js
> +    // },
Počistiti

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.js
> +}
Situacija gdje dobivamo null i tu se vrijednosti pokuša iterirati, pa vraća grešku.

Srediti da se localStorage item ne stvara dok se ne spremi prvi review, odnosno da ga se obriše nakon što se obriše zadnji review, radi higijene korisnikovog browsera.

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.js
> +        renderReviewList();
Rekli smo da bi optimalno bilo da se svaki put ne briše i ponovo rendera nova lista radi samo jednog dodanog reviewa.

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.js
> +    renderReviewList();
Takđer, treba li nam i ovdje pozivanje funkcije koja sve elemente briše, pa ponovo rendera?

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    max-width: 60%;
Širine div elemenata ne bih radio u postotcima. Eventualno nešto ovako:
```
width: 920px;
max-width: 100%;
```

Treba li nam ovdje `display: flex;`?

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    margin: 1% 0;
Margine isto ne bih radio kao postotke.

Staviti malo paddinga da sadržaj može disati.

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    width: 35%;
širina u postotcima

2024-07-04 14:00 UTC, ante-pesorda commented on homework-1/static/index.js
> +let mockReviews = [
promijeniti naziv varijable

2024-07-07 13:48 UTC, ante-pesorda approved these changes
Još samo par izmjena oko responzivnosti, pa može merge

2024-07-07 13:48 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    width: 920px;
Ovdje bi bilo bolje postaviti širinu kao 100% ako želimo da popuni širinu svog parenta.

2024-07-07 13:48 UTC, ante-pesorda commented on homework-1/static/index.html
> +        <link rel="icon" type="image/x-icon" href="../img/favicon-32x32.png">
Trebalo bi dodati meta viewport da se screen prilagodi širinama mobilnih uređaja:
`<meta name="viewport" content="width=device-width, initial-scale=1.0">`

2024-07-07 13:48 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    width: 920px;
`width` također možemo postaviti kao `100%`, nema potrebe bilo gdje postavljat 920px osim na containeru

2024-07-07 13:48 UTC, ante-pesorda commented on homework-1/static/styles.css
> +    width: 920px;
`width: 100%;`

2024-07-07 15:46 UTC, bokii2 commented
Dodao sam margine kod container da bi elementi disali kad imamo mobile view

2024-07-08 10:09 UTC, ante-pesorda approved these changes
Još jedna sitnica i možeš mergeat.
Odlično odrađeno ;)

2024-07-08 10:09 UTC, ante-pesorda commented on homework-1/static/index.js
> +    reviewListElement.innerHTML = '';
Ovo onda možemo maknuti
```suggestion

```

2024-07-08 19:04 UTC, merged