Homework 2
infinum-academy/js-react-academy-2024-bokii2 pull request #2
Opened 2024-07-08 13:24 UTC by bokii2

Funkcionalnosti su skoro gotovi. Uskoro stize i estetiku

2024-07-08 19:56 UTC, ante-pesorda commented
@bokii2 puca mi aplikacija kod pokretanja. Da obrišeš sadržaj localStoragea u dev toolsima pa pokušaš pofiksat?

<img width="758" alt="Screenshot 2024-07-08 at 21 56 06" src="https://github.com/infinum-academy/js-react-academy-2024-bokii2/assets/108664913/4cecc612-3560-4ba6-a8cf-570dc3fdc182">

2024-07-09 07:29 UTC, bokii2 commented
LocalStorage je fiksnat :)
Ponovio sam istu grešku od prošlog puta 🤦🏻‍♂️

2024-07-10 07:56 UTC, ante-pesorda requested changes
Sredili skupa na konzultacijama neke stvari, ali nismo stigli tipove, TS nam se crveni

2024-07-10 09:20 UTC, ante-pesorda approved these changes
Čini mi se da je TS sređen.
Odlično 🔥

2024-07-10 09:20 UTC, merged