Homework 4
infinum-academy/js-react-academy-2024-bokii2 pull request #5
Opened 2024-07-15 22:00 UTC by bokii2

2024-07-17 13:19 UTC, ante-pesorda requested changes

2024-07-17 13:19 UTC, ante-pesorda commented on homework-2/src/components/features/shows/ShowContainer/ShowContainer.tsx
> +            {data && <ShowDetails show={data} avgRating={averageRating} />}
Ovdje moraš prosljeđivati `data.show`
```suggestion
            {data && <ShowDetails show={data.show} avgRating={averageRating} />}
```

2024-07-17 13:47 UTC, bokii2 commented
Conflict-i su rjeseni

2024-07-17 13:50 UTC, bokii2 commented on homework-2/src/components/features/shows/ShowContainer/ShowContainer.tsx
> +            {data && <ShowDetails show={data} avgRating={averageRating} />}
Davao je error kad sam pokushao da uradim ovo. Sad je rjesheno 😃 🤦🏻‍♂️

2024-07-17 18:31 UTC, bokii2 commented
Gotovo je i spreman za razgledavanje

2024-07-20 13:34 UTC, ante-pesorda reviewed
Ne radi link na rgister
![Screenshot 2024-07-20 at 15 33 53](https://github.com/user-attachments/assets/4b1e989e-3df1-43a9-8977-b5c54603ce53)


Auth redirect ne radi najbolje
![Screenshot 2024-07-20 at 15 28 14](https://github.com/user-attachments/assets/6d691d8a-5a2c-462c-9b48-aa62d29ab8a6)

2024-07-20 14:03 UTC, ante-pesorda reviewed
Ok urađeno, ali treba pregledati komentare.
Malo srediti indentaciju i malo bolje testirati funkcionalnost.

Kad sam ulogiran, bi li ovdje trebao biti logout umjesto ovo dvoje?
![Screenshot 2024-07-20 at 15 43 21](https://github.com/user-attachments/assets/683d483c-c06a-4d82-9bc1-ebdff9b99da1)

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/app/log-out/page.tsx
Treba li nam page za logout?

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/app/my-profile/page.tsx
Dok se ne dovrši page, maknuo bih ga iz navigacije.

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/features/auth/LoginForm/LoginForm.tsx
> +                    }
U kojem trentuku se ovaj error postavlja na neku vrijednost, odnosno hoće li ikad bit vidljiv u layoutu?
Bi li ovdje trebalo slušati `onError` sa `useForm` hooka umjesto ovoga?

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/features/auth/RegisterForm/RegisterForm.tsx
> +    const [ error, setError ] = useState("");
Bi li errore trebali settati koristeći `setError` metodu sa `useForm` hooka umjesto ovako?

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/features/shows/ReviewForm/ReviewForm.tsx
> +    const [error, setError] = useState('')
Trebaju li nam više ovi stateovi ako koristimo `useForm` hook?

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/features/shows/ShowContainer/ShowContainer.tsx
> +        setAverageRating(calcAvgRating(loadedFromLS));
Dupla linija; obrisati

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/features/shows/ShowDetails/ShowDetails.tsx
> +            <Image alt="showImg" src={show.image_url} borderTopRadius='inherit' />
Na sliku uvijek stavljamo neki smisleni alternativni tekst, u slučaju da se slika iz nekog razloga ne učita
![Screenshot 2024-07-20 at 15 57 43](https://github.com/user-attachments/assets/bab967af-3356-4126-aa58-6a369f1be7a8)

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/shared/AuthRedirect/AuthRedirect.tsx
> +            console.log('Logged in, redirecting');
console.log-ove brišemo kad je PR spreman za review

2024-07-20 14:03 UTC, ante-pesorda commented on homework-2/src/components/shared/SidebarNavigation/SidebarNavigation.tsx
> +            {loggedIn && <Text as={NextLink} href={`/log-out`} onClick={handleLogout} mt='auto'>Log out</Text>}
Nakon što se ulogiram, u sidebaru su mi i dalje vidljivi Login i iRegister linkovi. Maknu se tek nakon refresha

2024-07-22 15:36 UTC, ante-pesorda approved these changes
Ovo sad možemo mergeat, pa ćemo ostalo u zadaći 5

2024-07-22 15:36 UTC, ante-pesorda commented on homework-2/src/components/features/shows/ShowCard/ShowCard.tsx
> +            <Image alt='showImg' src={show.image_url} width='100%' height='300px' borderTopRadius='inherit' />
```suggestion
            <Image alt={show.title} src={show.image_url} width='100%' height='300px' borderTopRadius='inherit' />

```

2024-07-22 15:39 UTC, merged